name: wic

channels:
  - conda-forge
  - defaults

dependencies:
# pypy is ~2X faster than the regular python interpreter.
# We need to install it first so the dependency solver installs it bundled with python 3.9
# (pypy is not yet compatible with 3.10 and 3.11)
  - pypy
  - "python<3.10"
# NOTE: cwltool needs nodejs for InlineJavascriptRequirement
  - nodejs
  - graphviz
# "Warning: Could not load "/miniconda/bin/../lib/graphviz/libgvplugin_pango.so.6"
#  - It was found, so perhaps one of its dependents was not.  Try ldd."
# See https://github.com/conda-forge/graphviz-feedstock/issues/35#issuecomment-786368065
  - xorg-libxrender
  - shellcheck
  - numpy
# wget and zip cause errors in the setup-miniconda github action on windows.
#  - wget
#  - zip