import json
import traceback
from pathlib import Path
import pytest
import yaml

import sophios
import sophios.plugins
from sophios import input_output as io
from sophios import utils, utils_cwl
from sophios.python_cwl_adapter import import_python_file
from sophios.schemas import wic_schema
from sophios.utils_yaml import wic_loader
from sophios.wic_types import Json


REPO_ROOT = Path(__file__).resolve().parent.parent
AUTOGENERATED_DIR = REPO_ROOT / "autogenerated"
PYTHON_WORKFLOW_MANIFEST = AUTOGENERATED_DIR / "python_workflow_manifest.json"


def _load_global_config() -> Json:
    config_file = Path().home() / "wic" / "global_config.json"
    return io.read_config_from_disk(config_file)


def _iter_python_workflow_paths(global_config: Json) -> list[tuple[str, Path]]:
    paths = sophios.plugins.get_py_paths(global_config)
    return [
        (path_str, path)
        for _, paths_dict in paths.items()
        for path_str, path in paths_dict.items()
        if "mm-workflows" not in str(path) and "docs/tutorials/" not in str(path)
    ]


def _write_manifest(workflow_paths: list[Path]) -> None:
    AUTOGENERATED_DIR.mkdir(parents=True, exist_ok=True)
    manifest = sorted({str(path) for path in workflow_paths})
    PYTHON_WORKFLOW_MANIFEST.write_text(json.dumps(manifest, indent=2), encoding="utf-8")


@pytest.mark.fast
def test_compile_python_workflows() -> None:
    """This function imports (read: blindly executes) all python files in 'search_paths_wic'
       The python files are assumed to have a top-level workflow() function
       which returns a sophios.apis.python.api.Workflow object.
       The python files should NOT call the .run() method!
       (from any code path that is automatically executed on import)
    """
    from sophios.apis.python import api  # pylint: disable=C0415:import-outside-toplevel
    # Since this is completely different test path we have to copy
    # default .txt files to default global_config.json
    global_config = _load_global_config()
    api.global_config = sophios.plugins.get_tools_cwl(global_config)  # Use path fallback in the CI
    paths_tuples = _iter_python_workflow_paths(global_config)
    import_errors: list[str] = []
    generated_workflows: list[Path] = []
    for path_stem, path in paths_tuples:
        # NOTE: Use anything (unique?) for the python_module_name.
        try:
            module = import_python_file(path_stem, path)
            # Let's require all python API files to define a function, say
            # def workflow() -> Workflow
            # so we can programmatically call it here:
            retval: api.Workflow = module.workflow()  # no arguments
            # which allows us to programmatically call Workflow methods:
            compiler_info = retval.compile()  # hopefully retval is actually a Workflow object!
            # But since this is python (i.e. not Haskell) that in no way eliminates
            # the above security considerations.

            # This lets us use path.parent to write a *.wic file in the
            # auto-discovery path, and thus reuse the existing wic CI
            retval.write_ast_to_disk(path.parent)
            generated_workflows.extend(path.parent / f"{wf.process_name}.wic" for wf in retval.flatten_subworkflows())

            # Programmatically blacklist subworkflows from running in config_ci.json
            # (Again, because subworkflows are missing inputs and cannot run.)
            config_ci = path.parent / 'config_ci.json'
            json_contents = {}
            if config_ci.exists():
                with open(config_ci, mode='r', encoding='utf-8') as r:
                    json_contents = json.load(r)
            run_blacklist: list[str] = json_contents.get('run_blacklist', [])
            # Use [1:] for proper subworkflows only
            subworkflows: list[api.Workflow] = retval.flatten_subworkflows()[1:]
            run_blacklist += [wf.process_name for wf in subworkflows]
            json_contents['run_blacklist'] = run_blacklist
            with open(config_ci, mode='w', encoding='utf-8') as f:
                json.dump(json_contents, f)

        except Exception as e:
            import_errors.append(f"{path_stem}: {type(e).__name__}: {e}")
            traceback.print_exception(type(e), value=e, tb=None)
    if import_errors:
        pytest.fail("Python workflow imports failed:\n" + "\n".join(import_errors))
    _write_manifest(generated_workflows)


@pytest.mark.fast
def test_validate_generated_python_workflows() -> None:
    if not PYTHON_WORKFLOW_MANIFEST.exists():
        pytest.fail(f"Missing generated workflow manifest: {PYTHON_WORKFLOW_MANIFEST}")

    global_config = _load_global_config()
    tools_cwl = sophios.plugins.get_tools_cwl(global_config)
    yml_paths = sophios.plugins.get_yml_paths(global_config)
    yaml_stems = utils.flatten([list(paths) for paths in yml_paths.values()])
    validator = wic_schema.get_validator(tools_cwl, yaml_stems, {}, write_to_disk=False)

    workflow_paths = json.loads(PYTHON_WORKFLOW_MANIFEST.read_text(encoding="utf-8"))
    validation_errors: list[str] = []
    for workflow_path_str in workflow_paths:
        workflow_path = Path(workflow_path_str)
        try:
            with workflow_path.open("r", encoding="utf-8") as handle:
                yaml_tree = yaml.load(handle.read(), Loader=wic_loader())
            validator.validate(utils_cwl.desugar_into_canonical_normal_form(yaml_tree))
        except Exception as exc:
            validation_errors.append(f"{workflow_path}: {type(exc).__name__}: {exc}")

    if validation_errors:
        pytest.fail("Generated workflow validation failed:\n" + "\n".join(validation_errors))
