# Use &filename to create a reference to an output. Inputs in later steps can
# use *filename to dereference the filename and create an explicit edge.
steps:
  - grompp:
      in:
        config: '{"mdp": {"integrator":"sd", "rvdw":"1.0", "rcoulomb":"1.0", "coulombtype":"pme", "nsteps":"100", "dt":0.002, "tc-grps":"system", "ref-t":"300", "tau-t":"2", "constraints":"h-bonds", "nstxout":"100", "pcoupl":"Berendsen", "tau-p":"1", "ref-p":"1", "compressibility":"4.5e-5"}}'
        output_tpr_path: '&prod.tpr'
        input_top_zip_path: '*genion.top'  # Use the original topology file so
# we don't have to question whether the topology gets messed up after file format conversions.
# (In fact, it is not exactly identical!)
  - mdrun:
      in:
        output_crd_path: '&prod.gro'