# See https://docs.github.com/en/actions/creating-actions/creating-a-javascript-action
name: 'Check existence'
description: 'Check for the existence of a given fork & branch'
inputs:
  repository:
    description: 'The name of the repository only (without owner)'
    type: string
    required: true
  sender_repo_owner:
    description: 'The name of the repository owner'
    type: string
    required: true
  sender_repo_ref:
    description: 'The name of the branch / ref'
    type: string
    required: true
  default_owner:
    description: 'The name of the default (i.e. the upstream) repository owner'
    type: string
    required: true
  default_branch:
    description: 'The name of the default (i.e. the upstream) branch'
    type: string
    required: true
  access_token:
    description: 'The token used for authentication'
    type: string
    required: true
outputs:
  repository:
    description: 'The name of the repository only (without owner)'
  owner:
    description: 'The name of the repository owner'
  ref:
    description: 'The name of the branch / ref'
runs:
  using: 'node16'
  main: 'dist/index.js'
