version: "0.0.2"

services:
  people:
    container_name: wic-api-new
    build:
      context: .
      dockerfile: ./Dockerfile_debian_rest_api
    working_dir: /workflow-inference-compiler
    command: uvicorn api:app --host 0.0.0.0 --port 3000 --reload
    environment:
      DEBUG: 1
    volumes:
      - ./:/workflow-inference-compiler
    ports:
      - 3000:3000
    restart: on-failure