apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wic-api.fullname" . }}
  labels:
    {{- include "wic-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: wic-api
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: wic-api
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
          - name: AUTH_BASE_URL
            value: {{ .Values.auth.baseUrl }}
          - name: ME_ENDPOINT
            value: {{ .Values.auth.meEndpoint }}
          - name: JWKS_ENDPOINT
            value: {{ .Values.auth.jwksEndpoint }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
