name: Branch Dispatch

on:
  pull_request:

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  branch_dispatch:
    runs-on: ubuntu-latest

    steps:
      - name: Create environment variables
        env:
          COMMIT_MESSAGE: ''
        run: |
          echo "commit_message=$COMMIT_MESSAGE" >> $GITHUB_ENV

      # Unbelievably, for pull requests only, there is apparently no way to get
      # the commit message directly via the github API.
      # See https://github.com/orgs/community/discussions/28474
      - name: Checkout commit sha (Pull Request only)
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit mesage (Pull Request only)
        run: |
          echo "commit_message=$(git show -s --format=%s)" >> $GITHUB_ENV

      - name: Check existence of wic
        uses: ./.github/my_actions/check_existence/ # Must start with ./
        id: ce_wic
        with:
          repository: workflow-inference-compiler
          sender_repo_owner: ${{ github.event.pull_request.head.repo.owner.login }}
          sender_repo_ref: ${{ github.event.pull_request.head.ref }}
          default_owner: PolusAI
          default_branch: master
          access_token: ${{ secrets.ACCESS_TOKEN }}

      # For other repositories, the entire step below should be copied and edited to make new steps.
      - name: Check existence of mm-workflows
        uses: ./.github/my_actions/check_existence/ # Must start with ./
        id: ce_mm-workflows
        with:
          repository: mm-workflows
          sender_repo_owner: ${{ github.event.pull_request.head.repo.owner.login }}
          sender_repo_ref: ${{ github.event.pull_request.head.ref }}
          default_owner: PolusAI
          default_branch: main
          access_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Branch dispatch build_and_test.yml
        uses: ./.github/my_actions/branch_dispatch/ # Must start with ./
        id: bd_build_and_test
        with:
          repository: workflow-inference-compiler
          workflow_yml: build_and_test.yml
          sender_repo: ${{ github.event.pull_request.head.repo.owner.login }}/${{ github.event.pull_request.head.repo.name }}
          sender_repo_owner: ${{ steps.ce_wic.outputs.owner }}
          sender_repo_ref: ${{ steps.ce_wic.outputs.ref }}
          event_type: ${{ github.event_name }}
          commit_message: ${{ env.commit_message }}  # NOTE: This may still be susceptible to script injection attacks.
          mm_workflows_owner: ${{ steps.ce_mm-workflows.outputs.owner }}
          mm_workflows_ref: ${{ steps.ce_mm-workflows.outputs.ref }}
          access_token: ${{ secrets.ACCESS_TOKEN }}

      - name: Branch dispatch build_and_run_workflows.yml
        uses: ./.github/my_actions/branch_dispatch/ # Must start with ./
        id: bd_build_and_run_workflows
        with:
          repository: workflow-inference-compiler
          workflow_yml: build_and_run_workflows.yml
          sender_repo: ${{ github.event.pull_request.head.repo.owner.login }}/${{ github.event.pull_request.head.repo.name }}
          sender_repo_owner: ${{ steps.ce_wic.outputs.owner }}
          sender_repo_ref: ${{ steps.ce_wic.outputs.ref }}
          event_type: ${{ github.event_name }}
          commit_message: ${{ env.commit_message }}  # NOTE: This may still be susceptible to script injection attacks.
          mm_workflows_owner: ${{ steps.ce_mm-workflows.outputs.owner }}
          mm_workflows_ref: ${{ steps.ce_mm-workflows.outputs.ref }}
          access_token: ${{ secrets.ACCESS_TOKEN }}
