name: Build And Run Test on Ubuntu

on:
  push:
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_PyTest:
    name: Build and Run PyTest
    runs-on: [self-hosted, linux]
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: wic
        channels: conda-forge
        python-version: "3.*"

    - name: Install System Dependencies from Conda
# The version of cwltool in apt (2.0.20200224214940) does not support CWL version 1.2
#      run: sudo apt install cwltool
# Use conda to install cwltool (version 3.1.20220224085855)
      working-directory: ${{github.workspace}}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        ./conda_devtools.sh

    - name: Install Workflow Inference Compiler
      working-directory: ${{github.workspace}}
      run: pip install ".[test]"

    - name: Run MyPy
      working-directory: ${{github.workspace}}
      # NOTE: Do not use `mypy .` because then mypy will check both src/ and build/ causing:
      # src/wic/__init__.py: error: Duplicate module named "wic" (also at "./build/lib/wic/__init__.py")
      # NOTE: We need to use --no-incremental because there is a bug in mypy.
      # This bug most often occurs when using ruamel library.
      # See https://github.com/python/mypy/issues/12664
      run: mypy --no-incremental src/ tests/

    - name: Run PyLint
      working-directory: ${{github.workspace}}
      # NOTE: See fail-under threshold in .pylintrc
      run: pylint src/ tests/

    - name: Run PyTest Serial Tests
      working-directory: ${{github.workspace}}
      run: pytest --cov -m serial --cov-config=.coveragerc_serial

    - name: Run PyTest Parallel Tests
      working-directory: ${{github.workspace}}
      run: pytest --cov -m "not serial" --workers 4 --cov-config=.coveragerc_parallel
