name: Build And Run Test on Ubuntu

on:
  push:
    branches: [ master ]
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  Build_and_Run_PyTest:
    name: Build and Run PyTest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Common Workflow Language
      run: sudo apt install cwltool
      
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"

    - name: Install Dependencies
      run: python -m pip install --upgrade graphviz pyyaml pytest

    - name: Install Workflow Inference Compiler
      working-directory: ${{github.workspace}}
      run: python3 setup.py install

    - name: Run PyTest
      working-directory: ${{github.workspace}}
      run: python3 -m pytest tests/