name: Build And Test

on:
  push:
  pull_request: 
  workflow_dispatch:

env:
  BUILD_TYPE: Release

defaults:
  run:
    shell: bash -l {0} # Invoke bash in login mode, NOT interactive mode.
    # This will cause bash to look for the startup file ~/.bash_profile, NOT ~/.bashrc
    # This is important since conda init writes to ~/.bashrc

# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions#jobs
# Rather than use a single job with a linear pipeline of steps, you may be
# tempted to make each step into a separate job and specify the dependencies
# using the `needs` syntax for more parallelism.
# However, data cannot be shared between jobs because each job will be run on a
# different runner. Even on a self-hosted runner, the `needs` syntax does not
# guarantee that the data can be shared!

# Using if: always() allows all steps to run, while still properly reporting failure.
# See https://stackoverflow.com/questions/62045967/github-actions-is-there-a-way-to-continue-on-error-while-still-getting-correct

jobs:
  build_and_test:
    # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    # This will prevent DOS attacks from people blasting the CI with rapid fire commits.
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout source code
        if: always()
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup mamba (linux, macos)
        if: runner.os != 'Windows'
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge-pypy3
          miniforge-version: latest
          environment-file: conda_devtools.yml
          activate-environment: wic
          use-mamba: true
          channels: conda-forge
          python-version: "3.9.*" # pypy is not yet compatible with 3.10 and 3.11

      - name: Setup conda (windows)
        if: runner.os == 'Windows'
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-version: latest
          environment-file: conda_devtools_windows.yml
          activate-environment: wic
          channels: conda-forge
          python-version: "3.9.*" # pypy is not yet compatible with 3.10 and 3.11

      - name: ShellCheck Script Quality
        if: always()
        # "SC1017 (error): Literal carriage return. Run script through tr -d '\r' ."
        run: shellcheck -e SC1017 $(find . -name "*.sh" -not -path "./biobb/*" -and -not -path "./3/*")

      - name: Install Workflow Inference Compiler (linux, macos)
        if: runner.os != 'Windows'
        run: pip install ".[all]"

      - name: Install Workflow Inference Compiler (windows)
        if: runner.os == 'Windows'
        run: pip install ".[test,doc]"

      - name: Install Workflow Inference Compiler runners (windows)
        if: runner.os == 'Windows'
        run: pip install ".[runners]"

      - name: Build Documentation
        if: always()
        run: cd docs && make html

      - name: MyPy Check Type Annotations
        if: always()
        run: mypy --no-incremental src/ tests/ api.py auth/
        # NOTE: Do not use `mypy .` because then mypy will check both src/ and build/ causing:
        # src/wic/__init__.py: error: Duplicate module named "wic" (also at "./build/lib/wic/__init__.py")
        # NOTE: We need to use --no-incremental because there is a bug in mypy.
        # This bug most often occurs when using ruamel library.
        # See https://github.com/python/mypy/issues/12664

      - name: PyLint Check Code Quality
        if: always()
        run: pylint src/ tests/ api.py auth/
        # NOTE: See fail-under threshold in .pylintrc

      - name: PEP8 Code Formatting
        if: always()
        id: autopep8
        run: autopep8 --exit-code --recursive --diff --max-line-length 120 examples/ src/ tests/ api.py auth/
      - name: Fail if autopep8 made changes
        if: steps.autopep8.outputs.exit-code == 2
        run: exit 1

  # NOTE: Do NOT add coverage to PYPY CI runs https://github.com/tox-dev/tox/issues/2252

      - name: PyTest CWL Embedding Independence
        if: always()
        run: pytest -k test_cwl_embedding_independence # --cov --cov-config=.coveragerc_serial
        # NOTE: This test MUST be run in serial! See is_isomorphic_with_timeout()
        timeout-minutes: 5 # backup timeout for windows

      - name: PyTest Inline Subworkflows
        if: always()
        run: pytest -k test_inline_subworkflows # --cov --cov-config=.coveragerc_serial
        # NOTE: This test MUST be run in serial! See is_isomorphic_with_timeout()
        timeout-minutes: 5 # backup timeout for windows

      - name: PyTest Fuzzy Compile Test
        if: always()
        run: pytest -k test_fuzzy_compile
