name: Fuzzy Compile

# The runtime of fuzzy compile can vary wildly, depending on whether the
# randomly chosen subschema is a CommandLineTool, a small workflow, or a
# complex workflow. So instead of running it on every push, do it on a schedule.

on:
  # push:  # Do NOT run fuzzy compile on every push!
  # pull_request: (either on origin or on upstream pull request)
  schedule:
    # Instead, run it every Wednesday at midnight.
      - cron: '0 0 * * 3'
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0} # Invoke bash in login mode, NOT interactive mode.
    # This will cause bash to look for the startup file ~/.bash_profile, NOT ~/.bashrc
    # This is important since conda init writes to ~/.bashrc

permissions:
  actions: read
  contents: read
  pull-requests: read

jobs:
  fuzzy_compile:
    # See https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#concurrency
    # This will prevent DOS attacks from people blasting the CI with rapid fire commits.
    concurrency:
      group: ${{ github.workflow }}-fuzzy-compile-${{ github.ref }}
      cancel-in-progress: true
    strategy:
      fail-fast: false
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout workflow-inference-compiler
        if: always()
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/workflow-inference-compiler
          ref: master
          path: wic

      - name: Checkout biobb_adapters
        if: always()
        uses: actions/checkout@v3
        with:
          repository: jfennick/biobb_adapters
          ref: master
          path: biobb_adapters

      - name: Checkout mm-workflows
        if: always()
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/mm-workflows
          ref: main
          path: mm-workflows

      - name: Setup mamba (linux, macos)
        if: runner.os != 'Windows'
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          miniforge-variant: Mambaforge-pypy3
          miniforge-version: latest
          environment-file: wic/install/system_deps.yml
          activate-environment: wic
          use-mamba: true
          channels: conda-forge
          python-version: "3.9.*" # pypy is not yet compatible with 3.10 and 3.11

      - name: Install Workflow Inference Compiler
        if: always()
        run: cd wic/ && pip install ".[all]"

      - name: Install Molecular Modeling Workflows
        if: always()
        # Also run mm-workflows command to generate
        # mm-workflows/autogenerated/schemas/config_schemas.json
        # NOTE: Use ".[test]" instead of ".[all]"
        # We do not want or need to install the workflow_deps extra.
        # (Many of the packages conflict with pypy.)
        run: cd mm-workflows/ && pip install ".[test]" && mm-workflows

# Since a randomly chosen subschema is used every time, repeat 10X for more coverage.

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile

      - name: PyTest Fuzzy Compile
        run: cd wic/ && pytest -k test_fuzzy_compile
