name: ".github/workflows/main.yml"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2

      - name: Create and activate conda environment
        run: |
          conda create --name wic
          conda activate wic

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
